import type { ResolvedEntity, ResolvedManifest, ResolvedRelationship } from "./types";

export class SQLGenerator {
  generate(manifest: ResolvedManifest): string {
    const lines: string[] = [];
    const entityCount = manifest.entities.length;
    const moduleKeys = Object.keys(manifest.module_versions).join(", ");

    // Header
    lines.push(`-- Generated by Next Gen Backend Generator`);
    lines.push(`-- Modules: ${moduleKeys}`);
    lines.push(`-- Entities: ${entityCount}`);
    lines.push(`-- Config: ${JSON.stringify(manifest.config_applied)}`);
    lines.push("");

    // Extensions
    lines.push(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`);
    lines.push(`CREATE EXTENSION IF NOT EXISTS pgcrypto;`);

    const hasVector = manifest.entities.some((e) =>
      e.fields.some((f) => f.type === "vector" || f.type.startsWith("vector("))
    );
    if (hasVector) {
      lines.push(`CREATE EXTENSION IF NOT EXISTS vector;`);
    }
    lines.push("");

    // Group entities by module for ordered output
    const moduleOrder: string[] = [];
    const moduleEntities = new Map<string, ResolvedEntity[]>();
    for (const entity of manifest.entities) {
      if (!moduleEntities.has(entity.module_key)) {
        moduleEntities.set(entity.module_key, []);
        moduleOrder.push(entity.module_key);
      }
      moduleEntities.get(entity.module_key)!.push(entity);
    }

    // CREATE TABLEs
    for (const modKey of moduleOrder) {
      const entities = moduleEntities.get(modKey)!;
      lines.push(`-- Module: ${modKey}`);

      for (const entity of entities) {
        lines.push(...this.generateTable(entity));
        lines.push("");
      }
    }

    // CREATE INDEXes
    const indexLines: string[] = [];
    for (const entity of manifest.entities) {
      for (const idx of entity.indexes) {
        const unique = idx.unique ? "UNIQUE " : "";
        indexLines.push(
          `CREATE ${unique}INDEX ${idx.name} ON ${entity.table} (${idx.columns.join(", ")});`
        );
      }
    }
    if (indexLines.length) {
      lines.push("-- Indexes");
      lines.push(...indexLines);
      lines.push("");
    }

    // FOREIGN KEYs
    const fkLines = this.generateForeignKeys(manifest.relationships);
    if (fkLines.length) {
      lines.push("-- Foreign Keys");
      lines.push(...fkLines);
      lines.push("");
    }

    return lines.join("\n");
  }

  private generateTable(entity: ResolvedEntity): string[] {
    const lines: string[] = [];
    const colDefs: string[] = [];

    for (const field of entity.fields) {
      let col = `  ${field.name} ${this.mapType(field.type)}`;

      if (field.pk) {
        col += " PRIMARY KEY";
        if (field.type === "uuid" && !field.default) {
          col += " DEFAULT gen_random_uuid()";
        }
      }

      if (!field.pk && field.nullable === false) {
        col += " NOT NULL";
      }

      if (field.unique && !field.pk) {
        col += " UNIQUE";
      }

      if (field.default) {
        col += ` DEFAULT ${this.formatDefault(field.default, field.type)}`;
      } else if (!field.pk && field.type === "timestamptz" && field.name.includes("created")) {
        col += " DEFAULT now()";
      }

      colDefs.push(col);
    }

    lines.push(`CREATE TABLE ${entity.table} (`);
    lines.push(colDefs.join(",\n"));
    lines.push(`);`);
    return lines;
  }

  private mapType(type: string): string {
    if (type === "int") return "integer";
    if (type.startsWith("vector")) return type; // vector(1536) passes through
    return type;
  }

  private formatDefault(
    defaultVal: string,
    fieldType: string
  ): string {
    // SQL functions pass through
    if (
      defaultVal === "now()" ||
      defaultVal === "gen_random_uuid()" ||
      defaultVal.startsWith("'") ||
      defaultVal === "true" ||
      defaultVal === "false" ||
      defaultVal === "0" ||
      !isNaN(Number(defaultVal))
    ) {
      return defaultVal;
    }

    // String values need quoting
    if (
      fieldType === "text" ||
      fieldType.startsWith("varchar") ||
      fieldType === "jsonb"
    ) {
      return `'${defaultVal}'`;
    }

    return defaultVal;
  }

  private generateForeignKeys(
    relationships: ResolvedRelationship[]
  ): string[] {
    return relationships.map((rel) => {
      const constraintName = `fk_${rel.from_table}_${rel.from_field}`;
      const onDelete = rel.on_delete ? ` ON DELETE ${rel.on_delete.toUpperCase()}` : "";
      return (
        `ALTER TABLE ${rel.from_table} ADD CONSTRAINT ${constraintName} ` +
        `FOREIGN KEY (${rel.from_field}) REFERENCES ${rel.to_table} (${rel.to_field})${onDelete};`
      );
    });
  }
}
